before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64le
      - mips64le
      - s390x
    goarm:
      - 5
      - 7
    gomips:
      - hardfloat
    ignore:
      - goos: windows
        goarch: 386
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
nfpms:
  -
    package_name: the-bastion-mkhash-helper
    vendor: OVH SAS
    maintainer: Stéphane Lesimple <stephane.lesimple+bastion@ovhcloud.com>
    description: Companion tool for The Bastion to generate hashes of specific hash types from given passwords
    license: Apache 2.0
    formats:
      - deb
      - rpm
    overrides:
      deb:
        file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}{{ if .Arm }}{{ .Arm }}{{ end }}"
        replacements:
          386: i386
          5: el
          7: hf
          mips64le: mips64el
      rpm:
        file_name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Arch }}{{ if .Arm }}{{ .Arm }}{{ end }}"
        replacements:
          386: i386
          amd64: x86_64
          arm64: aarch64
          5: v7l
          7: v7hnl
          mips64le: mips64el
